In [1]:
temp = [[1,4],[3,2],[0,8]]

In [2]:
sorted(temp, key=lambda i: i[1])

[[3, 2], [1, 4], [0, 8]]

In [3]:
sorted(temp, key=lambda i: i[0])

[[0, 8], [1, 4], [3, 2]]

In [4]:
import pandas as pd
import numpy as np

In [10]:
x = [1,2,3,4,5]
pd.Series(x)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
x= np.array([1,2,3,4,5])
pd.Series(x)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
print(x[0])
print(x[1:3])
print(x[::-1])
print(x[x>3])
print(x+1)
print(x*10)
print(x+x)

1
[2 3]
[5 4 3 2 1]
[4 5]
[2 3 4 5 6]
[10 20 30 40 50]
[ 2  4  6  8 10]


In [12]:
x = [1,2,3,4,5]
x=pd.Series(x)
print(x.index) # 인덱스 
print(x.values) # 값

RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]


In [17]:
x = [1, 2, 3, 4, 5]
x = pd.Series(x, index=['a','b','c','d','e'])
print(x['a']) # 명시적 인덱스접근
print(x[0]) # 묵시적 인덱스접근 
print(x['a':'e']) # 팬시색인, 한번에 여러값 접근 
print(x.a) # 또다른 접근방법

1
1
a    1
b    2
c    3
d    4
e    5
dtype: int64
1


In [19]:
x = {"수학":90, "영어":80, "과학":95, "미술":80} 
x = pd.Series(x)
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [20]:
x = pd.Series(x, index=["수학", "영어", "과학"])


수학    90
영어    80
과학    95
dtype: int64

In [25]:
print(x['수학'])

90


In [34]:
student_1 = {"수학": 90, "영어": 80, "과학": 95, "미술": 80} 
student_2 = {"수학": 70, "영어": 90, "과학": 100, "미술": 70}

index_1 = ['홍길동' for i in range(len(student_1))] + ['이몽룡' for i in range(len(student_2))]
#['홍길동', '홍길동', '홍길동', '홍길동', '이몽룡', '이몽룡', '이몽룡', '이몽룡']
index_2 = [i for i in student_1] + [i for i in student_2]
#['수학', '영어', '과학', '미술', '수학', '영어', '과학', '미술']
value_all = list(student_1.values()) + list(student_2.values()) 
students = pd.Series(value_all, index=[index_1, index_2])
print(value_all)
print(students)


[90, 80, 95, 80, 70, 90, 100, 70]
홍길동  수학     90
     영어     80
     과학     95
     미술     80
이몽룡  수학     70
     영어     90
     과학    100
     미술     70
dtype: int64


In [30]:
['홍길동' for i in range(len(student_1))] + ['이몽룡' for i in range(len(student_2))]

['홍길동', '홍길동', '홍길동', '홍길동', '이몽룡', '이몽룡', '이몽룡', '이몽룡']

In [32]:
[key for key in student_1]+[i for i in student_2]

['수학', '영어', '과학', '미술', '수학', '영어', '과학', '미술']

In [35]:
students['홍길동']

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [36]:
students['이몽룡']

수학     70
영어     90
과학    100
미술     70
dtype: int64