In [1]:
temp = [[1,4],[3,2],[0,8]]

In [2]:
sorted(temp, key=lambda i: i[1])

[[3, 2], [1, 4], [0, 8]]

In [3]:
sorted(temp, key=lambda i: i[0])

[[0, 8], [1, 4], [3, 2]]

In [4]:
import pandas as pd
import numpy as np

In [10]:
x = [1,2,3,4,5]
pd.Series(x)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
x= np.array([1,2,3,4,5])
pd.Series(x)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
print(x[0])
print(x[1:3])
print(x[::-1])
print(x[x>3])
print(x+1)
print(x*10)
print(x+x)

1
[2 3]
[5 4 3 2 1]
[4 5]
[2 3 4 5 6]
[10 20 30 40 50]
[ 2  4  6  8 10]


In [12]:
x = [1,2,3,4,5]
x=pd.Series(x)
print(x.index) # 인덱스 
print(x.values) # 값

RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]


In [17]:
x = [1, 2, 3, 4, 5]
x = pd.Series(x, index=['a','b','c','d','e'])
print(x['a']) # 명시적 인덱스접근
print(x[0]) # 묵시적 인덱스접근 
print(x['a':'e']) # 팬시색인, 한번에 여러값 접근 
print(x.a) # 또다른 접근방법

1
1
a    1
b    2
c    3
d    4
e    5
dtype: int64
1


In [19]:
x = {"수학":90, "영어":80, "과학":95, "미술":80} 
x = pd.Series(x)
x

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [20]:
x = pd.Series(x, index=["수학", "영어", "과학"])


수학    90
영어    80
과학    95
dtype: int64

In [25]:
print(x['수학'])

90


In [34]:
student_1 = {"수학": 90, "영어": 80, "과학": 95, "미술": 80} 
student_2 = {"수학": 70, "영어": 90, "과학": 100, "미술": 70}

index_1 = ['홍길동' for i in range(len(student_1))] + ['이몽룡' for i in range(len(student_2))]
#['홍길동', '홍길동', '홍길동', '홍길동', '이몽룡', '이몽룡', '이몽룡', '이몽룡']
index_2 = [i for i in student_1] + [i for i in student_2]
#['수학', '영어', '과학', '미술', '수학', '영어', '과학', '미술']
value_all = list(student_1.values()) + list(student_2.values()) 
students = pd.Series(value_all, index=[index_1, index_2])
print(value_all)
print(students)


[90, 80, 95, 80, 70, 90, 100, 70]
홍길동  수학     90
     영어     80
     과학     95
     미술     80
이몽룡  수학     70
     영어     90
     과학    100
     미술     70
dtype: int64


In [30]:
['홍길동' for i in range(len(student_1))] + ['이몽룡' for i in range(len(student_2))]

['홍길동', '홍길동', '홍길동', '홍길동', '이몽룡', '이몽룡', '이몽룡', '이몽룡']

In [32]:
[key for key in student_1]+[i for i in student_2]

['수학', '영어', '과학', '미술', '수학', '영어', '과학', '미술']

In [35]:
students['홍길동']

수학    90
영어    80
과학    95
미술    80
dtype: int64

In [36]:
students['이몽룡']

수학     70
영어     90
과학    100
미술     70
dtype: int64

In [3]:
%pip install folium

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.0/95.0 kB 3.2 MB/s eta 0:00:00
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
  Using cached MarkupSafe-2.1.1-cp310-cp310-macosx_10_9_universal2.whl (17 kB)
Note: you may need to restart the kernel to use updated packages.


In [4]:
import folium

seoul_map = folium.Map(location=[37.55,126.98], zoom_start=12)
seoul_map.save('./seoul.html')

In [7]:
import pandas as pd
import folium

df = pd.read_excel('./서울지역 대학교 위치.xlsx')
seoul_map = folium.Map(location=[37.55,126.98], zoom_start=12)

for name, lat, lng in zip(df.대학명, df.위도, df.경도):
    folium.Marker([lat,lng], popup=name).add_to(seoul_map)

seoul_map.save('./seoul_colleges.html')

In [10]:
import pandas as pd
import folium
import json

file_path = './경기도인구데이터.xlsx'
df = pd.read_excel(file_path, index_col='구분')
df.columns = df.columns.map(str)

geo_path = './경기도행정구역경계.json'
try:
    geo_data = json.load(open(geo_path, encoding='utf-8'))
except:
    geo_data = json.load(open(geo_path, encoding='utf-8-sig'))

g_map = folium.Map(location=[37.5502,126.982], tiles='Stamen Terrain', zoom_start=9)

year = '2007'

folium.Choropleth(geo_data=geo_data,
                data = df[year],
                columns=[df.index,df[year]],
                fill_color='YlOrRd', fill_opacity=0.7, line_opacity=0.3,
                threshold_scale=[10000,100000,300000,500000,700000],
                key_on='feature.properties.name',
                ).add_to(g_map)

g_map.save('./gyonggi_population_' + year + '.html')
