In [1]:
matrix_1=[ [1,2],[3,4] ]
matrix_2 =[ [5,6],[7,8] ]

# 예상 결과값 result=[[6,8],[10,12]]

In [2]:
row = 0
colum=0
matrix_1[row][colum]

result=[[0,0],[0,0]]

In [3]:
for row in range(2):
    for colum in range(2):
        result[row][colum]=matrix_1[row][colum]+matrix_2[row][colum]

In [4]:
result

[[6, 8], [10, 12]]

In [5]:
matrix_1

for row in range(2):
    for colum in range(2):
        matrix_1[row][colum]+=1

print(matrix_1)

[[2, 3], [4, 5]]


In [8]:
import numpy as np

matrix_1=[ [1,2],[3,4] ]
matrix_2 =[ [5,6],[7,8] ]

matrix_result = np.array(matrix_1) + np.array(matrix_2)
print(matrix_result)

[[ 6  8]
 [10 12]]


In [14]:
matrix_1=[ [1,2],[3,4] ]
matrix_1 = np.array(matrix_1) + 1
matrix_1 

array([[2, 3],
       [4, 5]])

In [18]:
import time
size = 10000000
# list
x = list(range(size)) 
y = list(range(size))
start_time = time.time()
z = [x[i]+y[i] for i in range(size)]
print('리스트 걸린시간', time.time() - start_time)
# adlist
x = np.arange(size)
y = np.arange(size) 
start_time = time.time()
z = x+y
print('넘파이 걸린시간', time.time() - start_time)

리스트 걸린시간 0.769294023513794
넘파이 걸린시간 0.08407306671142578


In [26]:
import numpy as np

x=np.uint(32)
print(x.dtype)
print(x)

x=np.array([1,2,3,4])
print(x.dtype)
x
print(x)

x=np.float32([1,2,3,4])
print(x.dtype)
x
print(x)

x=np.array([1,2,3,4],dtype=np.float32)
print(x.dtype)
x
print(x)


uint64
32
int64
[1 2 3 4]
float32
[1. 2. 3. 4.]
float32
[1. 2. 3. 4.]


In [27]:
x=np.uint(x)
x

array([1, 2, 3, 4], dtype=uint64)

In [28]:
x=np.array(1)
print(x.shape)
print(x.ndim)
print(x.size)

()
0
1


In [29]:
x=np.array([1,2])
print(x.shape)
print(x.ndim)
print(x.size)

(2,)
1
2


In [32]:
x=np.array([[1,2,3],[4,5,6]])
print(x.shape)
print(x.ndim)
print(x.size)

(2, 3)
2
6


In [36]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
x = np.arange(10.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [2]:
import numpy as np
x = np.arange(1,10,2)
print(x)

[1 3 5 7 9]


In [39]:
x = np.arange(1,10, 0.5)
x

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [44]:
x = np.arange(10,1,-0.5)
x

array([10. ,  9.5,  9. ,  8.5,  8. ,  7.5,  7. ,  6.5,  6. ,  5.5,  5. ,
        4.5,  4. ,  3.5,  3. ,  2.5,  2. ,  1.5])

In [3]:
np.linspace(1,20)

array([ 1.        ,  1.3877551 ,  1.7755102 ,  2.16326531,  2.55102041,
        2.93877551,  3.32653061,  3.71428571,  4.10204082,  4.48979592,
        4.87755102,  5.26530612,  5.65306122,  6.04081633,  6.42857143,
        6.81632653,  7.20408163,  7.59183673,  7.97959184,  8.36734694,
        8.75510204,  9.14285714,  9.53061224,  9.91836735, 10.30612245,
       10.69387755, 11.08163265, 11.46938776, 11.85714286, 12.24489796,
       12.63265306, 13.02040816, 13.40816327, 13.79591837, 14.18367347,
       14.57142857, 14.95918367, 15.34693878, 15.73469388, 16.12244898,
       16.51020408, 16.89795918, 17.28571429, 17.67346939, 18.06122449,
       18.44897959, 18.83673469, 19.2244898 , 19.6122449 , 20.        ])

In [52]:
np.linspace(1,20,5,endpoint=False)

array([ 1. ,  4.8,  8.6, 12.4, 16.2])

In [54]:
x=np.arange(9).reshape(3,-1)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [68]:
x=np.arange(20).reshape(4,-1)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [73]:
x=np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [76]:
x=np.array([[1,2],[3,4],[5,6]])
x.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
x = np.arange(20) 
print(x[1:3])

[1 2]


In [79]:
x = np.arange(20).reshape(4, 5) 
print(x)
print(x[1:3])
print(x[1:3, 1:3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 6  7]
 [11 12]]


In [80]:
x = np.arange(30).reshape(2, 5, 3) 
print(x)
print(x[:, 3:5, 1])
# print(x[:, 3:5, 1])에서 :는 전체를 선택하겠다는 뜻

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]
[[10 13]
 [25 28]]


In [81]:
x[:, 3:,:2]

array([[[ 9, 10],
        [12, 13]],

       [[24, 25],
        [27, 28]]])

In [82]:
x=np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [85]:
print(x[2][2]) # x의 2행 2열
print(x[2,2]) # x의 2행 2열


12
12


In [89]:
print(x[2,2],x[3,1])

12 16


In [95]:
print(x[x>3])
print(x[x==1])
print(x[~(x==1)]) #x가 1이 아닌 값을 찾음 ~는 아니다라는 뜻
print(x[(x > 3) & (x < 8)])

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[1]
[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[4 5 6 7]


In [105]:
np.random.rand(5,5)

array([[0.06442861, 0.01413091, 0.62801222, 0.65936438, 0.99997341],
       [0.98113936, 0.22371413, 0.33439358, 0.34018562, 0.18945604],
       [0.78575459, 0.44898917, 0.91304563, 0.45433857, 0.77032067],
       [0.2052961 , 0.35516291, 0.42878632, 0.0784726 , 0.97378822],
       [0.39453681, 0.08793552, 0.81996895, 0.59700358, 0.9460411 ]])

In [100]:
np.random.randint(1,10)

7

In [117]:
a=np.random.randint(1,10,size=(5))
print(a)


[8 5 1 9 3]


In [125]:
x.ravel(order='C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [130]:
x = np.arange(1,4).reshape(1,3)
y = np.arange(4,7).reshape(1,3)

In [131]:
x

array([[1, 2, 3]])

In [132]:
y

array([[4, 5, 6]])

In [142]:
z =np.concatenate([x,y], axis=0)
z

array([[1, 2, 3],
       [4, 5, 6]])

In [148]:
np.split(z,3 , axis=1)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [149]:
x= np.arange(1,10).reshape(3,3)
y=np.arange(1,4)
x+y

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [153]:
x= np.arange(0,10)+1
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [156]:
x = np.array([10,20,30]).reshape(3,1)

y=np.arange(1,4)
x+y

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])